name: release

on:
  workflow_dispatch :

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Configure git user name
        run: git config --global user.name "Benoit Maggi"
      - name: Configure git user email
        run: git config --global user.email "benoit.maggi@gmail.com"
      - name: Prepare release with Maven
        run: mvn --batch-mode release:clean release:prepare
